### PR TITLE
remove useless stuff

### PR DESCRIPTION
**Pull request by Stilic**
i removed a few useless files lol

### CODE REVIEW

**Comment by Stilic** [comment]
> most of these items aren't useless though lmao?

everything i removed was useless
what items do you mean then?

**Comment by BombasticTom** [comment]
changelog.md is used for base game updates, launch.bat launches yoshiengine for source, the art folder contains most of the yoshi engine assets, .hxproj has important project info

**Review by Luisinhi010 — APPROVED** [review]

**Review by MemeHoovy — APPROVED** [review]

**Comment by MemeHoovy** [comment]
why did you close this?

**Comment by Stilic** [comment]
> why did you close this?

yoshi engine is dead

**Pull request closed without merging**
