### PR TITLE
Workflows Merged into one

### PR DESCRIPTION
**Pull request by TheKitBoi**
Instead of spreate workflows there’s one that merged into one
It includes
Windows Compiler
Mac Compiler
Linux Compiler
HTML5 Compiler it can make a page to let you playtest it
Android Compiler

### CODE REVIEW

**Comment by adamsaustria** [comment]
@TheKitBoi is the mac one with mp4 support or no if no then its okay

**Comment by TheKitBoi** [comment]
> @TheKitBoi is the mac one with mp4 support or no if no then its okay

Not until the hxCoded is Updated

**Comment by MemeHoovy** [comment]
this engine is dead
https://twitter.com/FNFYoshiEngine/status/1576888881890590725

**Comment by TheKitBoi** [comment]
> this engine is dead
> https://twitter.com/FNFYoshiEngine/status/1576888881890590725

I know

**Pull request closed without merging**
